// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzZK-qlwRW0aqKd0HmRsqogttTkUOZF8I',
    appId: '1:64257621308:web:93739e770fd32a3e51b239',
    messagingSenderId: '64257621308',
    projectId: 'society-crm-672aa',
    authDomain: 'society-crm-672aa.firebaseapp.com',
    storageBucket: 'society-crm-672aa.firebasestorage.app',
    measurementId: 'G-C5SM1XD4ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzZK-qlwRW0aqKd0HmRsqogttTkUOZF8I',
    appId: '1:64257621308:web:93739e770fd32a3e51b239',
    messagingSenderId: '64257621308',
    projectId: 'society-crm-672aa',
    storageBucket: 'society-crm-672aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzZK-qlwRW0aqKd0HmRsqogttTkUOZF8I',
    appId: '1:64257621308:web:93739e770fd32a3e51b239',
    messagingSenderId: '64257621308',
    projectId: 'society-crm-672aa',
    storageBucket: 'society-crm-672aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzZK-qlwRW0aqKd0HmRsqogttTkUOZF8I',
    appId: '1:64257621308:web:93739e770fd32a3e51b239',
    messagingSenderId: '64257621308',
    projectId: 'society-crm-672aa',
    storageBucket: 'society-crm-672aa.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzZK-qlwRW0aqKd0HmRsqogttTkUOZF8I',
    appId: '1:64257621308:web:93739e770fd32a3e51b239',
    messagingSenderId: '64257621308',
    projectId: 'society-crm-672aa',
    authDomain: 'society-crm-672aa.firebaseapp.com',
    storageBucket: 'society-crm-672aa.firebasestorage.app',
    measurementId: 'G-C5SM1XD4ST',
  );
}
